[package]
name = "silence-with-sound"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
humantime = "2.1.0"
rand = "0.8.5"
rodio = "0.17.3"
